[project]
name = "api"
version = "0.1.0"
description = "API that provides random device measurement data"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.13",
    "fastapi-pagination>=0.13.2",
    "uvicorn>=0.29.0",
    "pydantic>=2.7.0",
]
